apiVersion: v1
kind: Secret
metadata:
  name: azure-cosmos-secret
  namespace: cloud-project
type: Opaque
stringData:
  AZURE_COSMOS_ENDPOINT: "https://<your-account>.documents.azure.com:443/"
  AZURE_COSMOS_KEY: "<your-cosmos-key>"
  AZURE_COSMOS_DATABASE: "cloudproject"
  AZURE_COSMOS_CATALOG_CONTAINER: "catalog"
  AZURE_COSMOS_CART_CONTAINER: "cart"

