apiVersion: v1
kind: Secret
metadata:
  name: azure-sql-secret
  namespace: cloud-project
type: Opaque
stringData:
  USER_SERVICE_DATASOURCE_URL: "jdbc:sqlserver://<your-server>.database.windows.net:1433;database=userdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
  INVENTORY_SERVICE_DATASOURCE_URL: "jdbc:sqlserver://<your-server>.database.windows.net:1433;database=inventorydb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
  ORDER_SERVICE_DATASOURCE_URL: "jdbc:sqlserver://<your-server>.database.windows.net:1433;database=orderdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
  AZURE_SQL_USERNAME: "<your-username>"
  AZURE_SQL_PASSWORD: "<your-password>"

