apiVersion: v1
kind: Secret
metadata:
  name: azure-entra-secret
  namespace: cloud-project
type: Opaque
stringData:
  AZURE_ENTRA_TENANT_ID: "dc1365e3-59f8-4188-865f-5e4607b295c4"
  AZURE_ENTRA_API_AUDIENCE: "api://ce89a7d0-8fae-45e3-b846-cb5eb435e883"
  AZURE_ENTRA_CLIENT_SECRET: "REPLACE_WITH_YOUR_CLIENT_SECRET"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "https://login.microsoftonline.com/dc1365e3-59f8-4188-865f-5e4607b295c4/v2.0"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES: "api://ce89a7d0-8fae-45e3-b846-cb5eb435e883"
