apiVersion: v1
kind: Secret
metadata:
  name: azure-servicebus-secret
  namespace: cloud-project
type: Opaque
stringData:
  AZURE_SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://<your-namespace>.servicebus.windows.net/;SharedAccessKeyName=<policy-name>;SharedAccessKey=<key>"
  AZURE_SERVICEBUS_QUEUE_NAME: "order-created"

