apiVersion: v1
kind: Secret
metadata:
  name: cosmos-secret
  namespace: cloud-project
type: Opaque
stringData:
  COSMOS_URI: "https://<your-cosmos-account>.documents.azure.com:443/"
  COSMOS_KEY: "<your-cosmos-key>"
  COSMOS_DB_PRODUCT: "productdb"
  COSMOS_DB_ORDER: "orderdb"