apiVersion: v1
kind: Secret
metadata:
  name: key-vault-secret
  namespace: cloud-project
type: Opaque
stringData:
  AZURE_KEY_VAULT_NAME: "<your-key-vault-name>"
  AZURE_KEY_VAULT_URI: "https://<your-key-vault-name>.vault.azure.net/"
  AZURE_WORKLOAD_IDENTITY_CLIENT_ID: "<workload-identity-client-id>"
  AZURE_TENANT_ID: "<tenant-id>"
