apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-secret
  namespace: cloud-project
type: Opaque
stringData:
  USER_SERVICE_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/userdb"
  INVENTORY_SERVICE_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/inventorydb"
  ORDER_SERVICE_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/orderdb"
  POSTGRES_DATASOURCE_USERNAME: "postgres"
  POSTGRES_DATASOURCE_PASSWORD: "postgres"

