apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloud-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: apnacloudproject.azurecr.io/product-service:v1
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/productdb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SERVER_PORT
              value: "8082"
            - name: AZURE_COSMOS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: azure-cosmos-secret
                  key: AZURE_COSMOS_ENDPOINT
            - name: AZURE_COSMOS_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-cosmos-secret
                  key: AZURE_COSMOS_KEY
            - name: AZURE_COSMOS_DATABASE
              valueFrom:
                secretKeyRef:
                  name: azure-cosmos-secret
                  key: AZURE_COSMOS_DATABASE
            - name: AZURE_COSMOS_CATALOG_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: azure-cosmos-secret
                  key: AZURE_COSMOS_CATALOG_CONTAINER
            - name: FEATURE_AZURE_SQL_ENABLED
              value: "false"
            - name: FEATURE_COSMOS_CATALOG_ENABLED
              value: "true"
            - name: FEATURE_COSMOS_CART_ENABLED
              value: "false"
            - name: FEATURE_SERVICEBUS_ENABLED
              value: "false"
            - name: FEATURE_AISEARCH_ENABLED
              value: "false"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: cloud-project
spec:
  selector:
    app: product-service
  ports:
    - port: 8082
      targetPort: 8082
